width:     400
height:    400
num_steps: 100

# ~5x faster but worse
fast_advect: True

# Initialization
init_s: pic.png
init_v: init_v_circular.npy

# Update parameters
solver_iters: 20
delta_t:      0.01
viscosity_k:  0.00001
diffusion_k:  0.0000001
dissipation:  0.01

# Render parameters
color_r:    0.0
color_g:    0.82
color_b:    1.0
out_folder: result
