width:     400
height:    400
num_steps: 100

# Faster but worse (?)
fast_advect: True

# Initialization
init_s: init_s_outerstar.npy
init_v: init_v_outerstar.npy

# Update parameters
solver_iters: 20
delta_t:      0.05
viscosity_k:  0
diffusion_k:  0
dissipation:  0
vorticity:    0

# Guiding parameters
guiding: True
target_v: init_v_outerstar.npy
guiding_alg: pd  # (initial, pd)
pd_params:
  tau:       0.4
  sigma:     1.1
  theta:     0.3
  max_iters: 20
  blur_size: 5
  guiding_w: 1.5

# Render parameters
color_r:    1.0
color_g:    0.82
color_b:    0.0
out_folder: result
write_vel:  True
write_init: True

# Export parameters
video_export:
  out_path: out.mov
  fps: 24
