width:     400
height:    400
num_steps: 100

# Faster but worse (?)
fast_advect: True

# Initialization
init_s: init_s_star.npy
init_v: init_v_star.npy

# Update parameters
solver_iters: 20
delta_t:      0.05
viscosity_k:  0
diffusion_k:  0
dissipation:  0

# Render parameters
color_r:    1.0
color_g:    0.82
color_b:    0.0
out_folder: result
write_vel:  True
